# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setting permissions
        run: chmod +x *.sh

      # Installs NGINX
      - name: Installing NGINX
        run: sudo ./install_nginx.sh

      # Installs Apache
      - name: Installing Apache
        run: sudo ./install_apache.sh

      # Installs MariaDB
      - name: Installing MariaDB
        run: sudo ./install_maria_db.sh

      # Installs NGINX
      - name: Installing PHP
        run: sudo ./install_php.sh